# This is an example mods.toml file. It contains the data relating to the loading mods.
modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="recipeplanner" #mandatory
version="0.1.0-alpha" #mandatory
displayName="Recipe Planner" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="examplemod.png" #optional
#credits="" #optional
authors="rafikus" #optional
description='''Mod for planning all steps for recipes.'''
[[dependencies.recipeplanner]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.recipeplanner]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.recipeplanner]]
    modId="jei"
    mandatory=true
    versionRange="[15.20.0,16.1.0)"
    ordering="NONE"
    side="BOTH"